import { Component, OnInit } from '@angular/core';
import { UserManagementService } from 'src/app/AuthGuard/Authentication/UserManagementService';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { ReportService } from '../report.service';
import {
  ApexChart,
  ApexXAxis,
  ApexTitleSubtitle,
  ApexDataLabels,
  ApexPlotOptions,
  ApexFill,
  ApexAxisChartSeries,
} from 'ng-apexcharts';

export type ChartOptions = {
  series: ApexAxisChartSeries;
  chart: ApexChart;
  xaxis: ApexXAxis;
  title: ApexTitleSubtitle;
  dataLabels: ApexDataLabels;
  plotOptions: ApexPlotOptions;
  fill: ApexFill;
  yaxis?: any;
  colors?: string[]; 
};

@Component({
  selector: 'app-un-sold-ticket-report',
  templateUrl: './un-sold-ticket-report.component.html',
  styleUrls: ['./un-sold-ticket-report.component.css']
})
export class UnSoldTicketReportComponent implements OnInit {
  UnsoldTickets: any[] = [];
  public chartOptions: ChartOptions;
  currentUserFullName:string="";
  reportGeneratedDateTime: string = "";
  public startDate: string = '';
  public endDate: string  = '';
  filteredUnsoldTickets=this.UnsoldTickets;
  

  constructor(
    private ticketSalesReportService: ReportService,
    private userManagementService:UserManagementService
  
  ) {
    this.chartOptions = {
      series: [
        {
          name: "Unsold Tickets",
          data: []
        }
      ],
      chart: {
        type: "bar",
        height: 350
      },
      plotOptions: {
        bar: {
          horizontal: false
        }
      },
      dataLabels: {
        enabled: false
      },
      xaxis: {
        categories: [],
        title: {
          text: 'Events' 
        }
      },
      yaxis: {
        title: {
          text: 'Number of Tickets' 
        }
      },
      title: {
        text: "Report on Unsold Tickets by Event"
      },
      fill: {
        opacity: 1
      }
    };
  }

  ngOnInit(): void {
    this.fetchTicketSalesReport();
   this.getUserFullNameAndDateTime();
  
    }
    getUserFullNameAndDateTime(): void {
      this.userManagementService.getUser().subscribe(response => {
        this.currentUserFullName = response.fullName; 
        this.reportGeneratedDateTime = new Date().toLocaleString(); // Get the current date and time
      }, error => {
        console.error('Error fetching user data', error);
        alert('Error fetching user data: ' + error.message);
      });
    }
    filterUnsoldTicketsByDate(): void {
      if (this.startDate || this.endDate) {
        this.filteredUnsoldTickets = this.UnsoldTickets.filter((ticket: { eventDate: string | number | Date; }) =>
          new Date(ticket.eventDate) >= new Date(this.startDate || '') &&
          new Date(ticket.eventDate) <= new Date(this.endDate || '')
        );
      } else {
        this.filteredUnsoldTickets = this.UnsoldTickets;
      }
      this.updateChartOptions(this.filteredUnsoldTickets);
    }

  exportToPDF(): void {
    const chartElement = document.getElementById('chart');
    const tableElement = document.getElementById('reportTable');
    const date = new Date().toLocaleDateString();
    const generatedBy = this.currentUserFullName; 
    
    if (chartElement && tableElement) {
      
      Promise.all([
        html2canvas(chartElement),
        html2canvas(tableElement)
      ]).then(([chartCanvas, tableCanvas]) => {
        const pdf = new jsPDF('p', 'mm', 'a4');
  
        
        pdf.setFontSize(18);
        pdf.text('Unsold Ticket Sales Report', 105, 20, { align: 'center' });
  
        pdf.setFontSize(12);
        pdf.text(`Date: ${date}`, 10, 30);
        pdf.text(`Generated by: ${generatedBy}`, 10, 35);
  
        
        const chartImgData = chartCanvas.toDataURL('image/png');
        const chartWidth = 180; 
        const chartHeight = (chartCanvas.height * chartWidth) / chartCanvas.width;
        pdf.addImage(chartImgData, 'PNG', 15, 40, chartWidth, chartHeight);
  
       
        const tableImgData = tableCanvas.toDataURL('image/png');
        const tableYPosition = 40 + chartHeight + 10; 
        const tableWidth = 180; 
        const tableHeight = (tableCanvas.height * tableWidth) / tableCanvas.width;
        pdf.addImage(tableImgData, 'PNG', 15, tableYPosition, tableWidth, tableHeight);
  
        pdf.save('UnsoldTicketSalesReport.pdf');
      }).catch(error => {
        console.error('Error generating PDF', error);
        alert('Error generating PDF: ' + error.message);
      });
    }
  }
  
  

  fetchTicketSalesReport(month: string = ''): void {
    this.ticketSalesReportService.getUnsoldTicketsReport(month).subscribe(
      (data: any[]) => {
        this.UnsoldTickets = data;
        this.updateChartOptions(data);
      },
      (error) => {
        console.error('Error fetching ticket sales report', error);
        alert('Error fetching ticket sales report: ' + error.message); 
      }
    );
  }
  updateChartOptions(data: any[]): void {
    const categories = data.map(item => item.eventName);
    const seriesData = data.map(item => item.unsoldTickets);
  
    // Define an array of colors for each bar
    const colors = ['#FF5733', '#33FF57', '#3357FF', '#F0F033', '#FF33F0', '#33FFF0']; // Adjust as needed
  
    this.chartOptions = {
      ...this.chartOptions,
      series: [
        {
          name: "Unsold Tickets",
          data: seriesData
        }
      ],
      xaxis: {
        categories: categories,
        title: {
          text: 'Events'
        }
      },
      yaxis: {
        title: {
          text: 'Number of Tickets'
        },
        labels: {
          formatter: (value: number) => value.toString()  
        }
      },
      colors: colors, // Apply different colors to the series
    };
  }
}