import { Component } from '@angular/core';
import { CodeServiceService } from '../service/code-service.service';
import { Router } from '@angular/router';

export interface CouponCode {
  couponCodeId: number;
  code: string;
  couponCodeDescription: string;
  discountAmount: number;
  sponsors: string;
}

@Component({
  selector: 'app-generate-code',
  templateUrl: './generate-code.component.html',
  styleUrls: ['./generate-code.component.css']
})
export class GenerateCodeComponent {

  description: string = '';
  discountAmount: number = 0;
  sponsors: string = '';
  generatedCouponCode: CouponCode | null = null;

  constructor(private couponCodeService: CodeServiceService, public router: Router) {}

  onSubmit(): void {
    const couponCodeData: CouponCode = {
      couponCodeId: 0, // Assuming this is generated by the backend
      code: '', // Assuming this is generated by the backend
      couponCodeDescription: this.description,
      discountAmount: this.discountAmount,
      sponsors: this.sponsors
    };

    this.couponCodeService.generateCouponCode(couponCodeData).subscribe(
      (couponCode: CouponCode) => {
        this.generatedCouponCode = couponCode;
        console.log(couponCode);
      }
    );
  }
}

